<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12/"
    xmlns:tns="http://www.agid.gov.it/ssu/ws/registry/service"
    
    targetNamespace="http://www.agid.gov.it/ssu/ws/registry/service">








    
    
</wsdl:definitions>